---
title: "volcano_plot"
author: "Brandon Beh Goh Beh"
date: "2024-02-22"
output: html_document
---

# Set the working directory
```{r}
setwd("/cloud/project/SURP_RPlots-master")
```
# Load the libraries
```{r}
library(ggplot2)
library(gplots)
```
# To include the entire path that goes to the desired file
```{r}
gene.transcript=read.csv("/cloud/project/SURP_RPlots-master/gene.description_sub.csv")
```
# Several commands to give some details/specification of file and data of interest
```{r}
#Check how many dimensions the dataset has (rows and columns)
dim(gene.transcript)

# Check what the column names are for the data
colnames(gene.transcript)

# To check what class of data is being used
class(gene.transcript)

# To look at the data set (Un-comment to view gene.transcript)
#View(gene.transcript)

```

#   2. Volcano Plots

# Making a volcano plot to look at the significant genes in the database
```{r}
# Plotting the volcano plot including labeling the red genes that exceed the adjusted p-value of 0.05
plot(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     las = 1, 
     xlim = c(-4,4),
     ylim = c(0,200),
     col = ifelse(gene.transcript$padj.L8_DOXvsL8<=0.05, "red", "black"),
     xlab = "log2 Fold Change",
     ylab = "-log10(p-value)",
     main = "Volcano Plot of L8")

# Then add your labels to your plot only for genes whos
# adjusted p-values that are less than or equal to 0.05 
# AND 
# log2 fold change that is 1.5 in the positive or negative direction
text(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     labels = ifelse(gene.transcript$padj.L8_DOXvsL8. <= 0.05 & abs(gene.transcript$log2FoldChange.L8_DOXvsL8.) >= 1.5, 
                     as.vector(gene.transcript$GeneName), NA),
     cex = 0.5, pos = 3)

# Adding a legend! (It doesn't matter which order the text/legend is done)
legend("topright", 
       legend = c("significant"), 
       pt.bg = c("red"), 
       bty = "n",
       pch = 21, 
       cex = 0.8)
```

#   3. Saving the Volcano Plot to a PDF

```{r}
# First you add the function pdf() with your chonen filename and .pdf
pdf("L8_DOXvsL8_VolcanoPlot.pdf")

plot(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     las = 1, 
     xlim = c(-4,4),
     ylim = c(0,200),
     col = ifelse(gene.transcript$padj.L8_DOXvsL8<=0.05, "red", "black"),
     xlab = "log2 Fold Change",
     ylab = "-log10(p-value)",
     main = "Volcano Plot of L8")
text(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     labels = ifelse(gene.transcript$padj.L8_DOXvsL8. <= 0.05 & abs(gene.transcript$log2FoldChange.L8_DOXvsL8.) >= 1.5, 
                     as.vector(gene.transcript$GeneName), NA),
     cex = 0.5, pos = 3)
legend("topright", 
       legend = c("significant"), 
       pt.bg = c("red"), 
       bty = "n",
       pch = 21, 
       cex = 0.8)

# Then closing the plot with the function dev.off()
dev.off()
```